### PR TITLE
[FIX] l10n_ar_stock: fix runbot error

### PR DESCRIPTION
**Pull request by vib-adhoc**
We have to adapt our code because of this Odoo commit: https://github.com/odoo/odoo/commit/2d62587c3ac6832e35f6f6d01d1c5b0eecd06f57

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/186).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#188

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#188

**Pull request closed without merging**
