### PR TITLE
[FIX] fix for pr https://github.com/odoo/odoo/commit/4633fd2840568112…

### PR DESCRIPTION
**Pull request by maq-adhoc**
…40180ea044daa5dcb8fd2ff9

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/165).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#166

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#166

**Pull request closed without merging**
