### PR TITLE
[FIX] l10n_ar_sale: inheritance fix

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/109).

**Comment by nicomacr** [comment]
@roboadhoc r+ override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
@nicomacr you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: you are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ee

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
