### PR TITLE
[FIX] l10n_ar_stock: Fix por cambio de clase en report_deliveryslip

### PR DESCRIPTION
**Pull request by mem-adhoc**
Ticket: 77528

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/190).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#191

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#191

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#191

**Pull request closed without merging**
