### PR TITLE
[MIG] l10n_ar_sale: Migration to 15.0

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/81).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/argentina-ce

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia. You are not allowed to override this status.

**Comment by jjscarafia** [comment]
@nicomacr nico, sabrás porque no se me emzcla esto

**Comment by nicomacr** [comment]
@jjscarafia le falta el merge method y además la falla del test de ci/argentina-ce, ya te di permiso para override.

Si le das de nuevo deberias poder. Voy a revisar por que el test ese no avanza

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ce

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
