### PR TITLE
[FIX] l10n_ar_sale: exclude taxes on backend

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/102).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia, you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/oba_without_tests override=ci/argentina-ee

se mezcla igual porque el error es por servicio externo

**Comment by roboadhoc** [comment]
@jjscarafia, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia. This PR is already reviewed, reviewing it again is useless. You are not allowed to override this status.

**Pull request merged**
