### PR TITLE
[MIG] l10n_ar_sale_order_type: Migration to 15.0

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/103).

**Review by nicomacr — APPROVED** [review]

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ee

**Comment by nicomacr** [comment]
@roboadhoc p=1

**Pull request closed without merging**
