### PR TITLE
[FW][FIX] l10n_ar_sale*: change the over of Write to the correct module to fulfill with dependencies

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/argentina-sale#82

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/83).

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ce

**Pull request closed without merging**
