### PR TITLE
[FIX] l10n_ar_sale: Discrimination of subtotal and amount in the sale…

### PR DESCRIPTION
**Pull request by lef-adhoc**
…s report depending on the tax discrimination

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/140).

**Comment by jok-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Comment by fw-bot-adhoc** [comment]
@jok-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#141

**Pull request closed without merging**
