### PR TITLE
[FW][FIX] l10n_ar_stock: report signature section adjustment

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/argentina-sale#119
Forward-Port-Of: ingadhoc/argentina-sale#112

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/120).

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral cherrypicking of pull request ingadhoc/argentina-sale#112 failed.

stdout:
```
Auto-merging l10n_ar_stock/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_stock/__manifest__.py

```

stderr:
```
19:19:05.716215 git.c:444               trace: built-in: git cherry-pick 42785bf144003b1a9e19f6a41332ae259082fa13
error: could not apply 42785bf... [FIX] l10n_ar_stock: report signature section adjustment
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
