### PR TITLE
[MIG] l10n_ar_stock_delivery: Migration to 16.0

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/114).

**Comment by jjscarafia** [comment]
se mezcla igual por ser warning de otro modulo
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
@roboadhoc r-

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Pull request closed without merging**
