### PR TITLE
[FIX] l10n_ar_sale*: change the over of Write to the correct module to fulfill with dependencies

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/82).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
