### PR TITLE
[IMP] l10n_ar_stock: add the possibility of force arba cuit and password

### PR DESCRIPTION
**Pull request by JoelZilli**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/107).

**Comment by JoelZilli** [comment]
@Bruno-Zanotti Después habría que mezclarlo a este

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Comment by fw-bot-adhoc** [comment]
@JoelZilli @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#111

**Pull request closed without merging**
