### PR TITLE
[ADD]l10n_ar_stock:data demo

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/127).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ --rebase-ff

**Comment by bruno-zanotti** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@jcadhoc @Bruno-Zanotti unable to stage: commits with multiple parents (760468a2b120248b5294e75f9b1c4d02b7f974d5) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by bruno-zanotti** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
