### PR TITLE
[FIX] l10n_ar_stock: report signature section adjustment

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/112).

**Review by zaoral — DISMISSED** [review]

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/112).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#119

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#120

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#120

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#120

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#120

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#120

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#120

**Pull request closed without merging**
