### PR TITLE
[FIX] l10n_ar_stock: add field translation

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/117).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#118

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/argentina-sale#118

**Pull request closed without merging**
