### PR TITLE
[FW][FIX] l10n_ar_stock: Fix por cambio de clase en report_deliveryslip

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 77528

Forward-Port-Of: ingadhoc/argentina-sale#190

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/191).

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral cherrypicking of pull request ingadhoc/argentina-sale#190 failed.

stdout:
```
Auto-merging l10n_ar_stock/views/report_deliveryslip.xml
CONFLICT (content): Merge conflict in l10n_ar_stock/views/report_deliveryslip.xml
Auto-merging l10n_ar_stock/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_stock/__manifest__.py

```

stderr:
```
16:35:39.444603 git.c:444               trace: built-in: git cherry-pick 28cd253163475fe810c3052fcd89e0c53c3a1ad1
error: could not apply 28cd253... [FIX] l10n_ar_stock: Fix por cambio de clase en report_deliveryslip
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
We are expecting a PR from odoo to merge in order to merge this one

**Comment by zaoral** [comment]
@roboadhoc r+
@roboadhoc override=ci/runbot-oba

NOTE: We force merge because PR is ok, the error is and external error on branch 17.0

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Pull request closed without merging**
