### PR TITLE
[FIX] l10n_ar_sale_order_type: fix varios

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/199).

**Comment by matiasperalta1** [comment]
@roboadhoc rebase-ff

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#200

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#200

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#200

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#200

**Pull request closed without merging**
