### PR TITLE
[ADD] l10n_ar_stock: COT in report_deliveryslip

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/133).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@mav-adhoc @jcadhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by jcadhoc** [comment]
@roboadhoc merge

**Comment by roboadhoc** [comment]
Merge method set to merge directly, using the PR as merge commit message.

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @jcadhoc: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
I'm sorry, @jcadhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
