### PR TITLE
Revert "[FIX] l10n_ar_stock: invoice print"

### PR DESCRIPTION
**Pull request by jjscarafia**
This reverts commit 521a03210327ea1c1a9b981ce7b998e4047d6e2c.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/108).

**Comment by jjscarafia** [comment]
se mezcla igual porque la nueva build fue bien (el warning es por otro modulo)
https://runbot.adhoc.com.ar/runbot/build/30037
@roboadhoc r+ override=ci/argentina-ee override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
@jjscarafia, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia. You are not allowed to override this status.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia. You are not allowed to override this status.

**Pull request merged**
