### PR TITLE
[FIX] l10n_ar_stock: ensure str field + add ssl to url

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/143).

**Comment by ALopez-Adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#146

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#146

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#146

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @ALopez-Adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/argentina-sale#146

**Pull request closed without merging**
