### PR TITLE
[FIX] l10n_ar_sale: Ahora get se usa con _get

### PR DESCRIPTION
**Pull request by mem-adhoc**
Major Version: 59

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/argentina-sale/pull/159).

**Comment by jjscarafia** [comment]
@roboadhoc r

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: r- makes no sense in the current PR state.

**Pull request closed without merging**
