### PR TITLE
[MIG] l10n_ar_sale: Migration to 16.0

### PR DESCRIPTION
**Pull request by ica-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
This PR targets the un-managed branch ingadhoc/argentina-sale:16.0, it needs to be retargeted before it can be merged.

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/argentina-sale/pull/110).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
